# 这是一个基本的工作流程，帮助你开始使用Actions

name: CI

# on 控制操作何时运行。
on:
  # 在push或pull请求事件上触发工作流，但仅适用于主分支
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  #允许您从Actions选项卡手动运行此工作流
  workflow_dispatch:

#工作流运行由一个或多个作业组成，这些作业可以顺序运行，也可以并行运行
jobs:
  #此工作流包含一个名为“build”的作业
  build:
    #作业将运行的运行程序类型
    runs-on: ubuntu-latest

    #步骤表示将作为作业的一部分执行的任务序列
    steps:
      #签出$GITHUB_WORKSPACE下的存储库，这样你的作业就可以访问它了
      - uses: actions/checkout@v2

      #使用运行程序shell运行单个命令
      - name: Run a one-line script
        run: echo Hello, world!

      #使用运行程序shell运行一组命令
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
